"""create ai business tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-15 23:00:07.876840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_api_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（钥匙主人；= account.id）'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='密钥串(含前缀；明文存，配唯一索引)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否启用；停用后立即失效'),
    sa.Column('remark', sa.String(length=255), server_default='', nullable=False, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_api_key_user_id', 'ai_api_key', ['user_id'], unique=False)
    op.create_index('uq_ai_api_key_api_key', 'ai_api_key', ['api_key'], unique=True)
    op.create_table('ai_api_tool_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('name', sa.String(length=64), server_default='', nullable=False, comment='工具提供者名（同用户内唯一）'),
    sa.Column('icon', sa.String(length=512), server_default='', nullable=False, comment='图标 URL'),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='提供者描述（取自 openapi schema）'),
    sa.Column('openapi_schema', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='原始 OpenAPI schema JSON 字符串'),
    sa.Column('headers', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='公共请求头 [{key,value}]'),
    sa.Column('source_public_id', sa.Integer(), nullable=True, comment='从哪条公共插件复制来（ai_public_plugin.id，软引用）；自建插件恒空。用于商店「是否已添加」去重'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_api_tool_provider_source_public_id', 'ai_api_tool_provider', ['source_public_id'], unique=False)
    op.create_index('ix_ai_api_tool_provider_user_id', 'ai_api_tool_provider', ['user_id'], unique=False)
    op.create_index('ix_ai_api_tool_provider_user_id_name', 'ai_api_tool_provider', ['user_id', 'name'], unique=False)
    op.create_table('ai_app',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='归属账号 id（= account.id，应用层按 current_user.id 过滤）；全局辅助 Agent 内置 app 为 NULL'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='应用名'),
    sa.Column('description', sa.String(length=512), server_default='', nullable=False, comment='应用描述'),
    sa.Column('icon', sa.String(length=512), server_default='', nullable=False, comment='图标 URL'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='当前用户的默认 app；get_or_create_default 使用'),
    sa.Column('is_assistant_agent', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='全局辅助 Agent 内置 app 标记（user_id 为 NULL，所有用户共享）'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='应用状态：draft / published（对齐 AppStatus）'),
    sa.Column('app_config_id', sa.Integer(), nullable=True, comment='已发布运行配置 id（→ai_app_config）；为空代表未发布'),
    sa.Column('draft_app_config_id', sa.Integer(), nullable=True, comment='草稿配置 id（→ai_app_config_version 中 config_type=draft 的那条）'),
    sa.Column('debug_conversation_id', sa.Integer(), nullable=True, comment='保留：调试会话 id（本轮调试链路仍走 get_or_create_for_app，不读此列）'),
    sa.Column('token', sa.String(length=32), nullable=True, comment='保留：已发布应用访问凭证（未来 WebApp 免登录用）'),
    sa.Column('source_public_app_id', sa.Integer(), nullable=True, comment='从哪条公共应用复制来（ai_public_app.id，软引用）；自建应用恒空。用于商店「是否已添加」去重'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_app_is_assistant_agent', 'ai_app', ['is_assistant_agent'], unique=False)
    op.create_index('ix_ai_app_source_public_app_id', 'ai_app', ['source_public_app_id'], unique=False)
    op.create_index('ix_ai_app_user_id', 'ai_app', ['user_id'], unique=False)
    op.create_index('ix_ai_app_user_id_is_default', 'ai_app', ['user_id', 'is_default'], unique=False)
    op.create_table('ai_dataset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('name', sa.String(length=128), server_default='', nullable=False, comment='知识库名（同用户内唯一）'),
    sa.Column('icon', sa.String(length=512), server_default='', nullable=False, comment='图标 URL'),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='知识库描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_dataset_user_id', 'ai_dataset', ['user_id'], unique=False)
    op.create_index('ix_ai_dataset_user_id_name', 'ai_dataset', ['user_id', 'name'], unique=False)
    op.create_table('ai_dataset_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='被查询的知识库'),
    sa.Column('query', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='查询语句'),
    sa.Column('source', sa.String(length=32), server_default='hit_testing', nullable=False, comment='来源：hit_testing / app（对齐 RetrievalSource）'),
    sa.Column('source_app_id', sa.Integer(), nullable=True, comment='来源应用 id（app 来源时填）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='发起者账号 id'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_dataset_query_dataset_id', 'ai_dataset_query', ['dataset_id'], unique=False)
    op.create_table('ai_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('type', sa.String(length=32), server_default='text2img', nullable=False, comment='生成类型：text2img / img2img'),
    sa.Column('provider', sa.String(length=64), server_default='', nullable=False, comment='模型 provider'),
    sa.Column('model', sa.String(length=128), server_default='', nullable=False, comment='模型名'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='提示词'),
    sa.Column('size', sa.String(length=32), server_default='', nullable=False, comment='尺寸，如 1024x1024'),
    sa.Column('input_image_url', sa.String(length=1024), server_default='', nullable=False, comment='图生图输入参考图 URL（文生图为空）'),
    sa.Column('url', sa.String(length=1024), server_default='', nullable=False, comment='生成图公网 URL'),
    sa.Column('mime_type', sa.String(length=128), server_default='', nullable=False, comment='MIME 类型'),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False, comment='文件大小(字节)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_image_user_id', 'ai_image', ['user_id'], unique=False)
    op.create_table('ai_keyword_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='所属知识库（唯一）'),
    sa.Column('keyword_table', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='{keyword: [segment_id,...]}'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_keyword_table_dataset_id', 'ai_keyword_table', ['dataset_id'], unique=True)
    op.create_table('ai_llm_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), server_default='', nullable=False, comment='唯一标识，全小写下划线'),
    sa.Column('label', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='多语言展示名 {zh_Hans,en_US}'),
    sa.Column('description', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='多语言描述'),
    sa.Column('icon', sa.String(length=512), server_default='', nullable=False, comment='icon URL（新建）或旧目录文件名'),
    sa.Column('background', sa.String(length=32), server_default='', nullable=False, comment='UI 主色背景，可选'),
    sa.Column('supported_model_types', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='["chat"/"text2img"/"tts"...]'),
    sa.Column('protocol', sa.String(length=32), server_default='openai', nullable=False, comment='须匹配协议注册表 key：openai/anthropic/volc_tts_ws'),
    sa.Column('multi_channel', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='true=走渠道池兜底（如第三方中转）'),
    sa.Column('base_url', sa.String(length=512), server_default='', nullable=False, comment='单渠道模式的 base_url'),
    sa.Column('api_key_cipher', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='单渠道模式 API Key 的 Fernet 密文'),
    sa.Column('api_key_env', sa.String(length=128), server_default='', nullable=False, comment='旧 env 变量名兜底（密文为空时回落）'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否启用（禁用则运行期/公开列表都不出现）'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='展示排序'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_llm_provider_name', 'ai_llm_provider', ['name'], unique=True)
    op.create_table('ai_process_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='所属知识库'),
    sa.Column('mode', sa.String(length=32), server_default='custom', nullable=False, comment='处理模式：automatic / custom（对齐 ProcessType）'),
    sa.Column('rule', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='{pre_process_rules, segment:{chunk_size,chunk_overlap,separators}}'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_process_rule_dataset_id', 'ai_process_rule', ['dataset_id'], unique=False)
    op.create_table('ai_public_app',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), server_default='', nullable=False, comment='应用名快照'),
    sa.Column('description', sa.String(length=512), server_default='', nullable=False, comment='应用描述快照'),
    sa.Column('icon', sa.String(length=512), server_default='', nullable=False, comment='图标 URL 快照'),
    sa.Column('preset_prompt', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='人设快照（冗余自 app_config，便于卡片展示）'),
    sa.Column('app_config', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='sanitize 后的 14 字段完整配置（添加时直接喂建应用流程的 config_overrides）'),
    sa.Column('model_provider', sa.String(length=64), server_default='', nullable=False, comment='展示快照：模型 provider'),
    sa.Column('model_name', sa.String(length=128), server_default='', nullable=False, comment='展示快照：模型名'),
    sa.Column('tool_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='展示快照：内置工具数'),
    sa.Column('category', sa.String(length=32), server_default='', nullable=False, comment='分类（预留，先空）'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序权重，大在前'),
    sa.Column('published_by', sa.Integer(), nullable=False, comment='发布者账号 id（= account.id）'),
    sa.Column('source_app_id', sa.Integer(), nullable=False, comment='来源私有 app id（软引用，无 FK）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ai_public_app_source_app_id', 'ai_public_app', ['source_app_id'], unique=True)
    op.create_table('ai_public_plugin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), server_default='', nullable=False, comment='插件名'),
    sa.Column('icon', sa.String(length=512), server_default='', nullable=False, comment='图标 URL'),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='插件描述'),
    sa.Column('openapi_schema', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='原始 OpenAPI schema（复制到私有用）'),
    sa.Column('headers', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='公共请求头 [{key,value}]'),
    sa.Column('tools', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='工具展示快照 [{name,description,inputs}]'),
    sa.Column('category', sa.String(length=32), server_default='', nullable=False, comment='分类（预留，先空）'),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排序权重，大在前'),
    sa.Column('published_by', sa.Integer(), nullable=False, comment='发布者账号 id（= account.id）'),
    sa.Column('source_provider_id', sa.Integer(), nullable=False, comment='来源私有 provider id（软引用，无 FK）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ai_public_plugin_source_provider_id', 'ai_public_plugin', ['source_provider_id'], unique=True)
    op.create_table('ai_upload_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('name', sa.String(length=512), server_default='', nullable=False, comment='原始文件名'),
    sa.Column('key', sa.String(length=512), server_default='', nullable=False, comment='存储相对路径（相对 STORAGE_ROOT）'),
    sa.Column('size', sa.Integer(), server_default='0', nullable=False, comment='文件大小(字节)'),
    sa.Column('extension', sa.String(length=64), server_default='', nullable=False, comment='扩展名(小写,不带点)'),
    sa.Column('mime_type', sa.String(length=128), server_default='', nullable=False, comment='MIME 类型'),
    sa.Column('hash', sa.String(length=128), server_default='', nullable=False, comment='内容哈希'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_upload_file_user_id', 'ai_upload_file', ['user_id'], unique=False)
    op.create_table('ai_workflow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('name', sa.String(length=64), server_default='', nullable=False, comment='展示名'),
    sa.Column('tool_call_name', sa.String(length=64), server_default='', nullable=False, comment='工具调用名（英文标识符，同用户内唯一；暴露给 LLM 时加 wf_ 前缀）'),
    sa.Column('icon', sa.String(length=512), server_default='', nullable=False, comment='图标 URL'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述（给 LLM 判断何时调用）'),
    sa.Column('graph', sa.JSON(), nullable=False, comment='发布版图配置（运行时只读它）'),
    sa.Column('draft_graph', sa.JSON(), nullable=False, comment='草稿图配置（编辑器读写）'),
    sa.Column('is_debug_passed', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='调试是否通过（发布闸门；改草稿即重置）'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("('draft')"), nullable=False, comment='draft / published'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tool_call_name', name='uq_ai_workflow_user_tool_call_name')
    )
    op.create_index('ix_ai_workflow_user_id', 'ai_workflow', ['user_id'], unique=False)
    op.create_table('ai_api_tool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='所属 provider'),
    sa.Column('name', sa.String(length=128), server_default='', nullable=False, comment='工具名（OpenAPI operationId）'),
    sa.Column('description', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='工具描述'),
    sa.Column('url', sa.String(length=512), server_default='', nullable=False, comment='请求 URL（server + path）'),
    sa.Column('method', sa.String(length=16), server_default='get', nullable=False, comment='HTTP 方法 get/post'),
    sa.Column('parameters', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='参数列表 [{name,in,description,required,type}]'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_api_tool_provider.id'], name='fk_ai_api_tool_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_api_tool_provider_id_name', 'ai_api_tool', ['provider_id', 'name'], unique=False)
    op.create_index('ix_ai_api_tool_user_id', 'ai_api_tool', ['user_id'], unique=False)
    op.create_table('ai_app_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False, comment='所属 ai_app'),
    sa.Column('model_config', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='{provider, model, parameters}'),
    sa.Column('dialog_round', sa.Integer(), server_default=sa.text('3'), nullable=False, comment='上下文携带轮数'),
    sa.Column('preset_prompt', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='系统提示词 / AI 人设'),
    sa.Column('tools', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='保留：工具列表'),
    sa.Column('workflows', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='保留：工作流列表'),
    sa.Column('datasets', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='保留：知识库列表'),
    sa.Column('retrieval_config', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='保留：检索配置'),
    sa.Column('long_term_memory', sa.JSON(), server_default=sa.text('(\'{"enable": false}\')'), nullable=False, comment='长期记忆配置'),
    sa.Column('opening_statement', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='开场白'),
    sa.Column('opening_questions', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='开场建议问题'),
    sa.Column('speech_to_text', sa.JSON(), server_default=sa.text('(\'{"enable": false}\')'), nullable=False, comment='保留：语音转文本'),
    sa.Column('text_to_speech', sa.JSON(), server_default=sa.text('(\'{"enable": false}\')'), nullable=False, comment='保留：文本转语音'),
    sa.Column('suggested_after_answer', sa.JSON(), server_default=sa.text('(\'{"enable": true}\')'), nullable=False, comment='答后建议'),
    sa.Column('review_config', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='保留：审核配置'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ai_app.id'], name='fk_ai_app_config_app', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_app_config_app_id', 'ai_app_config', ['app_id'], unique=False)
    op.create_table('ai_app_config_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False, comment='所属 ai_app'),
    sa.Column('model_config', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='{provider, model, parameters}'),
    sa.Column('dialog_round', sa.Integer(), server_default=sa.text('3'), nullable=False, comment='上下文携带轮数'),
    sa.Column('preset_prompt', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='系统提示词 / AI 人设'),
    sa.Column('tools', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='保留：工具列表'),
    sa.Column('workflows', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='保留：工作流列表'),
    sa.Column('datasets', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='保留：知识库列表'),
    sa.Column('retrieval_config', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='保留：检索配置'),
    sa.Column('long_term_memory', sa.JSON(), server_default=sa.text('(\'{"enable": false}\')'), nullable=False, comment='长期记忆配置'),
    sa.Column('opening_statement', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='开场白'),
    sa.Column('opening_questions', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='开场建议问题'),
    sa.Column('speech_to_text', sa.JSON(), server_default=sa.text('(\'{"enable": false}\')'), nullable=False, comment='保留：语音转文本'),
    sa.Column('text_to_speech', sa.JSON(), server_default=sa.text('(\'{"enable": false}\')'), nullable=False, comment='保留：文本转语音'),
    sa.Column('suggested_after_answer', sa.JSON(), server_default=sa.text('(\'{"enable": true}\')'), nullable=False, comment='答后建议'),
    sa.Column('review_config', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='保留：审核配置'),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='发布版本号；草稿为 0'),
    sa.Column('config_type', sa.String(length=32), server_default='draft', nullable=False, comment='配置类型：draft / published（对齐 AppConfigType）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ai_app.id'], name='fk_ai_app_config_version_app', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_app_config_version_app_id', 'ai_app_config_version', ['app_id'], unique=False)
    op.create_index('ix_ai_app_config_version_app_id_config_type', 'ai_app_config_version', ['app_id', 'config_type'], unique=False)
    op.create_table('ai_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='所属知识库'),
    sa.Column('upload_file_id', sa.Integer(), nullable=True, comment='对应 ai_upload_file.id（普通引用，不 FK）'),
    sa.Column('process_rule_id', sa.Integer(), nullable=True, comment='对应 ai_process_rule.id（普通引用，不 FK）'),
    sa.Column('batch', sa.String(length=32), server_default='', nullable=False, comment='处理批次（一次上传共享，供状态轮询）'),
    sa.Column('name', sa.String(length=512), server_default='', nullable=False, comment='文档名'),
    sa.Column('position', sa.Integer(), server_default='1', nullable=False, comment='文档在知识库内的位序'),
    sa.Column('character_count', sa.Integer(), server_default='0', nullable=False, comment='字符数'),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False, comment='token 数'),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True, comment='开始处理时间'),
    sa.Column('parsing_completed_at', sa.DateTime(), nullable=True, comment='解析完成时间'),
    sa.Column('splitting_completed_at', sa.DateTime(), nullable=True, comment='分割完成时间'),
    sa.Column('indexing_completed_at', sa.DateTime(), nullable=True, comment='索引完成时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='全部完成时间'),
    sa.Column('stopped_at', sa.DateTime(), nullable=True, comment='停止/出错时间'),
    sa.Column('error', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='错误信息'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否启用（命中检索）'),
    sa.Column('disabled_at', sa.DateTime(), nullable=True, comment='禁用时间'),
    sa.Column('status', sa.String(length=32), server_default='waiting', nullable=False, comment='对齐 DocumentStatus: waiting/parsing/splitting/indexing/completed/error'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['ai_dataset.id'], name='fk_ai_document_dataset', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_document_dataset_id', 'ai_document', ['dataset_id'], unique=False)
    op.create_index('ix_ai_document_dataset_id_batch', 'ai_document', ['dataset_id', 'batch'], unique=False)
    op.create_index('ix_ai_document_user_id', 'ai_document', ['user_id'], unique=False)
    op.create_table('ai_end_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='租户=钥匙主人账号 id（= account.id）'),
    sa.Column('app_id', sa.Integer(), nullable=False, comment='所属 ai_app(终端用户只在某 app 下存在)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ai_app.id'], name='fk_ai_end_user_app', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_end_user_app_id', 'ai_end_user', ['app_id'], unique=False)
    op.create_index('ix_ai_end_user_user_id', 'ai_end_user', ['user_id'], unique=False)
    op.create_table('ai_llm_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='所属提供商'),
    sa.Column('name', sa.String(length=128), server_default='', nullable=False, comment='渠道备注名'),
    sa.Column('base_url', sa.String(length=512), server_default='', nullable=False, comment='该渠道 base_url'),
    sa.Column('api_key_cipher', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='该渠道 API Key 的 Fernet 密文'),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False, comment='越小越先试'),
    sa.Column('models', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='支持的 model_name 白名单，空=全部'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_llm_provider.id'], name='fk_ai_llm_channel_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_llm_channel_provider_priority', 'ai_llm_channel', ['provider_id', 'priority'], unique=False)
    op.create_table('ai_llm_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='所属提供商'),
    sa.Column('model_name', sa.String(length=128), server_default='', nullable=False, comment='上游 SDK 的 model 参数'),
    sa.Column('label', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='多语言展示名'),
    sa.Column('model_type', sa.String(length=32), server_default='chat', nullable=False, comment='chat/text2img/tts/embedding...'),
    sa.Column('features', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='["tool_call","vision","streaming"...]'),
    sa.Column('context_window', sa.Integer(), server_default='4096', nullable=False, comment='上下文窗口'),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True, comment='单次最大输出 tokens'),
    sa.Column('parameter_rules', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='可调参数规则'),
    sa.Column('pricing', sa.JSON(), nullable=True, comment='{input,output,unit,currency}，可空'),
    sa.Column('deprecated', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否弃用（列表里会过滤）'),
    sa.Column('admin_only', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='仅特定权限可调（如文生图）'),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否该类型默认模型（展示用）'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='是否启用'),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False, comment='展示排序'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_llm_provider.id'], name='fk_ai_llm_model_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_llm_model_provider_id', 'ai_llm_model', ['provider_id'], unique=False)
    op.create_index('ix_ai_llm_model_provider_model', 'ai_llm_model', ['provider_id', 'model_name'], unique=True)
    op.create_table('ai_workflow_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True, comment='预留：应用内调用的来源应用 id（现阶段只有调试页写行，恒为 NULL）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='触发者账号 id（= account.id）'),
    sa.Column('workflow_id', sa.Integer(), nullable=False, comment='关联工作流 id'),
    sa.Column('graph', sa.JSON(), nullable=False, comment='运行时图快照（工作流后续改/删不影响历史回放）'),
    sa.Column('state', sa.JSON(), nullable=False, comment='全部节点的 NodeResult 列表'),
    sa.Column('latency', sa.Float(), server_default=sa.text('0'), nullable=False, comment='总耗时（秒）'),
    sa.Column('status', sa.String(length=32), server_default=sa.text("('running')"), nullable=False, comment='running / succeeded / failed'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['ai_workflow.id'], name='fk_ai_workflow_result_workflow', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_workflow_result_app_id', 'ai_workflow_result', ['app_id'], unique=False)
    op.create_index('ix_ai_workflow_result_user_id', 'ai_workflow_result', ['user_id'], unique=False)
    op.create_table('ai_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False, comment='所属 ai_app'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('title', sa.String(length=128), server_default='新会话', nullable=False, comment='会话标题'),
    sa.Column('invoke_from', sa.String(length=32), server_default='web_app', nullable=False, comment='调用入口；对齐 InvokeFrom 枚举'),
    sa.Column('created_by', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='创建者账号 id；本轮 = user_id'),
    sa.Column('end_user_id', sa.Integer(), nullable=True, comment='终端用户 id（仅开放 API service_api 会话有值；站内会话为 NULL）'),
    sa.Column('summary', sa.Text(), nullable=True, comment='长期记忆摘要'),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否置顶'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='软删标记'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ai_app.id'], name='fk_ai_conversation_app', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['end_user_id'], ['ai_end_user.id'], name='fk_ai_conversation_end_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_conversation_app_id', 'ai_conversation', ['app_id'], unique=False)
    op.create_index('ix_ai_conversation_user_app_pinned_updated', 'ai_conversation', ['user_id', 'app_id', 'is_pinned', 'updated_at'], unique=False)
    op.create_index('ix_ai_conversation_user_id_updated_at', 'ai_conversation', ['user_id', 'updated_at'], unique=False)
    op.create_table('ai_segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属账号 id（= account.id）'),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='所属知识库（冗余，便于全文检索/清理，不 FK）'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='所属文档'),
    sa.Column('node_id', sa.String(length=64), server_default='', nullable=False, comment='Qdrant 向量点 id（uuid）'),
    sa.Column('position', sa.Integer(), server_default='1', nullable=False, comment='片段在文档内的位序'),
    sa.Column('content', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='片段内容'),
    sa.Column('character_count', sa.Integer(), server_default='0', nullable=False, comment='字符数'),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False, comment='token 数'),
    sa.Column('keywords', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='关键词列表'),
    sa.Column('hash', sa.String(length=128), server_default='', nullable=False, comment='内容哈希（判断是否需重建向量）'),
    sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False, comment='被检索命中次数'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否启用'),
    sa.Column('disabled_at', sa.DateTime(), nullable=True, comment='禁用时间'),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('indexing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='错误信息'),
    sa.Column('status', sa.String(length=32), server_default='waiting', nullable=False, comment='对齐 SegmentStatus: waiting/indexing/completed/error'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ai_document.id'], name='fk_ai_segment_document', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_segment_dataset_id', 'ai_segment', ['dataset_id'], unique=False)
    op.create_index('ix_ai_segment_document_id', 'ai_segment', ['document_id'], unique=False)
    op.create_index('ix_ai_segment_node_id', 'ai_segment', ['node_id'], unique=False)
    op.create_table('ai_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False, comment='所属 ai_app'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='所属会话'),
    sa.Column('invoke_from', sa.String(length=32), server_default='web_app', nullable=False, comment='调用入口；对齐 InvokeFrom 枚举'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者账号 id；本轮 = user_id'),
    sa.Column('end_user_id', sa.Integer(), nullable=True, comment='终端用户 id（软引用；仅开放 API service_api 消息有值，站内消息为 NULL）'),
    sa.Column('query', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='用户提问'),
    sa.Column('answer', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='AI 回答全文'),
    sa.Column('image_urls', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='图片附件 URL 列表'),
    sa.Column('file_infos', sa.JSON(), nullable=True, comment='文档附件 [{url,name,extension,text}]（text 为截断后抽取缓存；旧行 NULL=[]）'),
    sa.Column('message', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='预留：LLM 实际输入消息序列'),
    sa.Column('provider', sa.String(length=64), nullable=True, comment='LLM provider'),
    sa.Column('model_name', sa.String(length=64), nullable=True, comment='LLM model'),
    sa.Column('latency', sa.Float(), server_default=sa.text('0'), nullable=False, comment='总耗时(秒)'),
    sa.Column('status', sa.String(length=32), server_default='normal', nullable=False, comment='对齐 MessageStatus 枚举: normal/stop/timeout/error'),
    sa.Column('error', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='异常信息'),
    sa.Column('message_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('message_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0'), nullable=False),
    sa.Column('message_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('answer_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('answer_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0'), nullable=False),
    sa.Column('answer_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('total_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='软删标记'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ai_app.id'], name='fk_ai_message_app', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversation.id'], name='fk_ai_message_conversation', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_message_app_id', 'ai_message', ['app_id'], unique=False)
    op.create_index('ix_ai_message_conversation_id_created_at', 'ai_message', ['conversation_id', 'created_at'], unique=False)
    op.create_table('ai_message_agent_thought',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('invoke_from', sa.String(length=32), server_default='web_app', nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='创建者账号 id（软引用）'),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='步骤序号'),
    sa.Column('event', sa.String(length=32), server_default='', nullable=False, comment='对齐 QueueEvent 名'),
    sa.Column('thought', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='LLM 思考'),
    sa.Column('observation', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='工具/RAG 输出'),
    sa.Column('tool', sa.Text(), server_default=sa.text("('')"), nullable=False, comment='工具名'),
    sa.Column('tool_input', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='工具入参'),
    sa.Column('message', sa.JSON(), server_default=sa.text("('[]')"), nullable=False, comment='该步骤 prompt'),
    sa.Column('message_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('message_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0'), nullable=False),
    sa.Column('message_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('answer', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('answer_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('answer_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0'), nullable=False),
    sa.Column('answer_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('total_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0'), nullable=False),
    sa.Column('latency', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ai_app.id'], name='fk_ai_message_agent_thought_app', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversation.id'], name='fk_ai_message_agent_thought_conversation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ai_message.id'], name='fk_ai_message_agent_thought_message', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_message_agent_thought_app_id', 'ai_message_agent_thought', ['app_id'], unique=False)
    op.create_index('ix_ai_message_agent_thought_conversation_id', 'ai_message_agent_thought', ['conversation_id'], unique=False)
    op.create_index('ix_ai_message_agent_thought_message_id', 'ai_message_agent_thought', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_message_agent_thought_message_id', table_name='ai_message_agent_thought')
    op.drop_index('ix_ai_message_agent_thought_conversation_id', table_name='ai_message_agent_thought')
    op.drop_index('ix_ai_message_agent_thought_app_id', table_name='ai_message_agent_thought')
    op.drop_table('ai_message_agent_thought')
    op.drop_index('ix_ai_message_conversation_id_created_at', table_name='ai_message')
    op.drop_index('ix_ai_message_app_id', table_name='ai_message')
    op.drop_table('ai_message')
    op.drop_index('ix_ai_segment_node_id', table_name='ai_segment')
    op.drop_index('ix_ai_segment_document_id', table_name='ai_segment')
    op.drop_index('ix_ai_segment_dataset_id', table_name='ai_segment')
    op.drop_table('ai_segment')
    op.drop_index('ix_ai_conversation_user_id_updated_at', table_name='ai_conversation')
    op.drop_index('ix_ai_conversation_user_app_pinned_updated', table_name='ai_conversation')
    op.drop_index('ix_ai_conversation_app_id', table_name='ai_conversation')
    op.drop_table('ai_conversation')
    op.drop_index('ix_ai_workflow_result_user_id', table_name='ai_workflow_result')
    op.drop_index('ix_ai_workflow_result_app_id', table_name='ai_workflow_result')
    op.drop_table('ai_workflow_result')
    op.drop_index('ix_ai_llm_model_provider_model', table_name='ai_llm_model')
    op.drop_index('ix_ai_llm_model_provider_id', table_name='ai_llm_model')
    op.drop_table('ai_llm_model')
    op.drop_index('ix_ai_llm_channel_provider_priority', table_name='ai_llm_channel')
    op.drop_table('ai_llm_channel')
    op.drop_index('ix_ai_end_user_user_id', table_name='ai_end_user')
    op.drop_index('ix_ai_end_user_app_id', table_name='ai_end_user')
    op.drop_table('ai_end_user')
    op.drop_index('ix_ai_document_user_id', table_name='ai_document')
    op.drop_index('ix_ai_document_dataset_id_batch', table_name='ai_document')
    op.drop_index('ix_ai_document_dataset_id', table_name='ai_document')
    op.drop_table('ai_document')
    op.drop_index('ix_ai_app_config_version_app_id_config_type', table_name='ai_app_config_version')
    op.drop_index('ix_ai_app_config_version_app_id', table_name='ai_app_config_version')
    op.drop_table('ai_app_config_version')
    op.drop_index('ix_ai_app_config_app_id', table_name='ai_app_config')
    op.drop_table('ai_app_config')
    op.drop_index('ix_ai_api_tool_user_id', table_name='ai_api_tool')
    op.drop_index('ix_ai_api_tool_provider_id_name', table_name='ai_api_tool')
    op.drop_table('ai_api_tool')
    op.drop_index('ix_ai_workflow_user_id', table_name='ai_workflow')
    op.drop_table('ai_workflow')
    op.drop_index('ix_ai_upload_file_user_id', table_name='ai_upload_file')
    op.drop_table('ai_upload_file')
    op.drop_index('uq_ai_public_plugin_source_provider_id', table_name='ai_public_plugin')
    op.drop_table('ai_public_plugin')
    op.drop_index('uq_ai_public_app_source_app_id', table_name='ai_public_app')
    op.drop_table('ai_public_app')
    op.drop_index('ix_ai_process_rule_dataset_id', table_name='ai_process_rule')
    op.drop_table('ai_process_rule')
    op.drop_index('ix_ai_llm_provider_name', table_name='ai_llm_provider')
    op.drop_table('ai_llm_provider')
    op.drop_index('ix_ai_keyword_table_dataset_id', table_name='ai_keyword_table')
    op.drop_table('ai_keyword_table')
    op.drop_index('ix_ai_image_user_id', table_name='ai_image')
    op.drop_table('ai_image')
    op.drop_index('ix_ai_dataset_query_dataset_id', table_name='ai_dataset_query')
    op.drop_table('ai_dataset_query')
    op.drop_index('ix_ai_dataset_user_id_name', table_name='ai_dataset')
    op.drop_index('ix_ai_dataset_user_id', table_name='ai_dataset')
    op.drop_table('ai_dataset')
    op.drop_index('ix_ai_app_user_id_is_default', table_name='ai_app')
    op.drop_index('ix_ai_app_user_id', table_name='ai_app')
    op.drop_index('ix_ai_app_source_public_app_id', table_name='ai_app')
    op.drop_index('ix_ai_app_is_assistant_agent', table_name='ai_app')
    op.drop_table('ai_app')
    op.drop_index('ix_ai_api_tool_provider_user_id_name', table_name='ai_api_tool_provider')
    op.drop_index('ix_ai_api_tool_provider_user_id', table_name='ai_api_tool_provider')
    op.drop_index('ix_ai_api_tool_provider_source_public_id', table_name='ai_api_tool_provider')
    op.drop_table('ai_api_tool_provider')
    op.drop_index('uq_ai_api_key_api_key', table_name='ai_api_key')
    op.drop_index('ix_ai_api_key_user_id', table_name='ai_api_key')
    op.drop_table('ai_api_key')
    # ### end Alembic commands ###
